name: fabrications

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  fabrications:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports fabrications 
      uses: ./
      with:
        config: fabrications.kibot.yaml
        dir: test
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: gerber"
      run: |
        test -f test/gerbers/*B_CrtYd.gbr && \
        test -f test/gerbers/*F_CrtYd.gbr && \
        test -f test/gerbers/*B_Cu.gbr && \
        test -f test/gerbers/*F_Cu.gbr && \
        test -f test/gerbers/*B_Mask.gbr && \
        test -f test/gerbers/*F_Mask.gbr && \
        test -f test/gerbers/*B_Paste.gbr && \
        test -f test/gerbers/*F_Paste.gbr && \
        test -f test/gerbers/*B_SilkS.gbr && \
        test -f test/gerbers/*F_SilkS.gbr && \
        test -f test/gerbers/*B_CrtYd.gbr && \
        test -f test/gerbers/*F_CrtYd.gbr
    - name: "check output: gerber"
      run: |
        test -f test/gerbers/*NPTH*.gbr && \
        test -f test/gerbers/*NPTH*.drl && \
        test -f test/gerbers/*-PTH*.gbr && \
        test -f test/gerbers/*-PTH*.drl
    - name: "check output: position"
      run: |
        test -f test/gerbers/*_pos.csv
    - name: "check output: bom"
      run: |
        test -f test/gerbers/*_BOM.csv
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: gerbers
        path: |
          test/gerbers/*
          drc*
          *.rpt
