name: test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports docs
      uses: ./
      with:
        config: docs.kiplot.yaml
        dir: test
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: docs"
      run: |
        test -f test/docs/test-Schematic*.svg && \
        test -f test/docs/test-Schematic*.pdf && \
        test -f test/docs/test-Board*.pdf
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: docs
        path: test/docs/*

  bom:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports bom
      uses: ./
      with:
        config: bom.kiplot.yaml
        dir: test
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: bom"
      run: |
        test -f test/docs/bom/test*.html && \
        test -f test/docs/bom/test*.csv && \
        test -f test/docs/bom/test*.xlsx
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: bom
        path: test/docs/bom/*

  fabrications:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports fabrications 
      uses: ./
      with:
        config: fabrications.kiplot.yaml
        dir: test
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: fabrications"
      run: |
        test -f test/gerbers/*B_CrtYd.gbr && \
        test -f test/gerbers/*F_CrtYd.gbr && \
        test -f test/gerbers/*B_Cu.gbr && \
        test -f test/gerbers/*F_Cu.gbr && \
        test -f test/gerbers/*B_Mask.gbr && \
        test -f test/gerbers/*F_Mask.gbr && \
        test -f test/gerbers/*B_Paste.gbr && \
        test -f test/gerbers/*F_Paste.gbr && \
        test -f test/gerbers/*B_SilkS.gbr && \
        test -f test/gerbers/*F_SilkS.gbr && \
        test -f test/gerbers/*B_CrtYd.gbr && \
        test -f test/gerbers/*F_CrtYd.gbr && \
        test -f test/gerbers/*NPTH*.gbr && \
        test -f test/gerbers/*NPTH*.drl && \
        test -f test/gerbers/*-PTH*.gbr && \
        test -f test/gerbers/*-PTH*.drl && \
        test -f test/gerbers/*_pos.csv
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: gerbers
        path: test/gerbers/*, test/*.rpt

  plot:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports plot
      uses: ./
      with:
        config: plot.kiplot.yaml
        dir: test
        schema: test/test.sch
        board: test/test.kicad_pcb
    - name: "check output: plot"
      run: |
        test -f test/docs/img/test-top.svg && \
        test -f test/docs/img/test-bottom.svg 
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: img
        path: test/docs/img/*
